services:
  - type: web
    name: todo-server
    env: node
    plan: free
    branch: main
    autoDeploy: true
    buildCommand: npm --prefix server run build:client
    startCommand: node server/index.js
    envVars:
      - key: MONGO_URI
        value: "REPLACE_WITH_YOUR_MONGO_URI"
